services:
  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    environment:
      - PORT=:8000
      - CONFIG_FILE=/app/config.json
    volumes:
      - ./config.json:/app/config.json
    ports:
      - 8000:8000
  jsonendpoint:
    build:
      context: .
      dockerfile: jsonendpoint.Dockerfile
    environment:
      - PORT=:8000
    ports:
      - 8001:8000
